In [1]:
import dask
from dask.distributed import Client

In [2]:
client = Client(n_workers=4, threads_per_worker=1, memory_limit='2GB')
client

/opt/anaconda3/lib/python3.12/site-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 54650 instead
  warnings.warn(

In [3]:
import dask
df = dask.datasets.timeseries()

/opt/anaconda3/lib/python3.12/site-packages/dask_expr/_collection.py:5833: UserWarning: dask_expr does not support the DataFrameIOFunction protocol for column projection. To enable column projection, please ensure that the signature of `func` includes a `columns=` keyword argument instead.
  warnings.warn(

In [4]:
df

Dask DataFrame Structure:
                  name     id        x        y
npartitions=30
2000-01-01      string  int64  float64  float64
2000-01-02         ...    ...      ...      ...
...                ...    ...      ...      ...
2000-01-30         ...    ...      ...      ...
2000-01-31         ...    ...      ...      ...
Dask Name: to_string_dtype, 2 expressions
Expr=ArrowStringConversion(frame=FromMap(8ef37c1))

In [5]:
df.compute().head(5)

2026-02-20 00:46:02,133 - distributed.worker - ERROR - failed during get data with tcp://127.0.0.1:54662 -> tcp://127.0.0.1:54665
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/tornado/iostream.py", line 962, in _handle_write
    num_bytes = self.write_to_fd(self._write_buffer.peek(size))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/tornado/iostream.py", line 1124, in write_to_fd
    return self.socket.send(data)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 55] No buffer space available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/worker.py", line 1783, in get_data
    response = await comm.read(deserializers=serializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://127.0.0.1:54662 remote=tcp://127.0.0.1:54676>: OSError: [Errno 55] No buffer space available
2026-02-20 00:46:02,136 - distributed.worker - ERROR - failed during get data with tcp://127.0.0.1:54663 -> tcp://127.0.0.1:54665
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/tornado/iostream.py", line 962, in _handle_write
    num_bytes = self.write_to_fd(self._write_buffer.peek(size))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/tornado/iostream.py", line 1124, in write_to_fd
    return self.socket.send(data)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 55] No buffer space available

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/worker.py", line 1783, in get_data
    response = await comm.read(deserializers=serializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 140, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc.__class__.__name__}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed)  local=tcp://127.0.0.1:54663 remote=tcp://127.0.0.1:54677>: OSError: [Errno 55] No buffer space available
2026-02-20 00:46:02,137 - distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.0.1:54663
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 230, in read
    buffer = await read_bytes_rw(stream, buffer_nbytes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 366, in read_bytes_rw
    actual = await stream.read_into(chunk)  # type: ignore[arg-type]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/worker.py", line 2059, in gather_dep
    response = await get_data_from_worker(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/worker.py", line 2863, in get_data_from_worker
    response = await send_recv(
               ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/core.py", line 1154, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Ephemeral Worker->Worker for gather local=tcp://127.0.0.1:54677 remote=tcp://127.0.0.1:54663>: Stream is closed
2026-02-20 00:46:02,140 - distributed.worker - ERROR - Worker stream died during communication: tcp://127.0.0.1:54662
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 230, in read
    buffer = await read_bytes_rw(stream, buffer_nbytes)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 366, in read_bytes_rw
    actual = await stream.read_into(chunk)  # type: ignore[arg-type]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tornado.iostream.StreamClosedError: Stream is closed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/worker.py", line 2059, in gather_dep
    response = await get_data_from_worker(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/worker.py", line 2863, in get_data_from_worker
    response = await send_recv(
               ^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/core.py", line 1154, in send_recv
    response = await comm.read(deserializers=deserializers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 236, in read
    convert_stream_closed_error(self, e)
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 142, in convert_stream_closed_error
    raise CommClosedError(f"in {obj}: {exc}") from exc
distributed.comm.core.CommClosedError: in <TCP (closed) Ephemeral Worker->Worker for gather local=tcp://127.0.0.1:54676 remote=tcp://127.0.0.1:54662>: Stream is closed

                         name    id         x         y
timestamp
2000-01-01 00:00:00     Alice   894  0.386141  0.508339
2000-01-01 00:00:01  Patricia   956  0.577245  0.246441
2000-01-01 00:00:02    Oliver   999 -0.413937 -0.431332
2000-01-01 00:00:03     Quinn  1057 -0.271495 -0.728492
2000-01-01 00:00:04       Tim   969 -0.837131 -0.451577

Use Standard Pandas Operations.

In [7]:
df2 = df[df.y > 0]
df2

Dask DataFrame Structure:
                  name     id        x        y
npartitions=30
2000-01-01      string  int64  float64  float64
2000-01-02         ...    ...      ...      ...
...                ...    ...      ...      ...
2000-01-30         ...    ...      ...      ...
2000-01-31         ...    ...      ...      ...
Dask Name: getitem, 5 expressions
Expr=Filter(frame=ArrowStringConversion(frame=FromMap(8ef37c1)), predicate=ArrowStringConversion(frame=FromMap(8ef37c1))['y'] > 0)

In [8]:
df3 = df2.groupby("name").x.std()
df3

Dask Series Structure:
npartitions=1
    float64
        ...
Dask Name: getitem, 8 expressions
Expr=(((Filter(frame=ArrowStringConversion(frame=FromMap(8ef37c1)), predicate=ArrowStringConversion(frame=FromMap(8ef37c1))['y'] > 0))[['name', 'x']]).std(ddof=1, numeric_only=False, split_out=None, observed=False))['x']

In [9]:
df3.compute()

2026-02-20 00:46:02,830 - distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 128, in unpackb
    ret = unpacker._unpack()
          ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 565, in _unpack
    ret.append(self._unpack(EX_CONSTRUCT))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 585, in _unpack
    key = self._unpack(EX_CONSTRUCT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 546, in _unpack
    typ, n, obj = self._read_header()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 447, in _read_header
    self._reserve(1)
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 420, in _reserve
    raise OutOfData
msgpack.exceptions.OutOfData

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/protocol/core.py", line 175, in loads
    return msgpack.loads(
           ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 130, in unpackb
    raise ValueError("Unpack failed: incomplete input")
ValueError: Unpack failed: incomplete input
2026-02-20 00:46:02,835 - distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 128, in unpackb
    ret = unpacker._unpack()
          ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 565, in _unpack
    ret.append(self._unpack(EX_CONSTRUCT))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 585, in _unpack
    key = self._unpack(EX_CONSTRUCT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 546, in _unpack
    typ, n, obj = self._read_header()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 447, in _read_header
    self._reserve(1)
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 420, in _reserve
    raise OutOfData
msgpack.exceptions.OutOfData

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/core.py", line 970, in _handle_comm
    result = await result
             ^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/scheduler.py", line 5710, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/core.py", line 1025, in handle_stream
    msgs = await comm.read()
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 247, in read
    msg = await from_frames(
          ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/utils.py", line 78, in from_frames
    res = _from_frames()
          ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/utils.py", line 61, in _from_frames
    return protocol.loads(
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/protocol/core.py", line 175, in loads
    return msgpack.loads(
           ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 130, in unpackb
    raise ValueError("Unpack failed: incomplete input")
ValueError: Unpack failed: incomplete input
Task exception was never retrieved
future: <Task finished name='Task-82' coro=<Server._handle_comm() done, defined at /opt/anaconda3/lib/python3.12/site-packages/distributed/core.py:876> exception=ValueError('Unpack failed: incomplete input')>
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 128, in unpackb
    ret = unpacker._unpack()
          ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 565, in _unpack
    ret.append(self._unpack(EX_CONSTRUCT))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 585, in _unpack
    key = self._unpack(EX_CONSTRUCT)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 546, in _unpack
    typ, n, obj = self._read_header()
                  ^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 447, in _read_header
    self._reserve(1)
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 420, in _reserve
    raise OutOfData
msgpack.exceptions.OutOfData

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/core.py", line 970, in _handle_comm
    result = await result
             ^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/scheduler.py", line 5710, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/core.py", line 1025, in handle_stream
    msgs = await comm.read()
           ^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 247, in read
    msg = await from_frames(
          ^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/utils.py", line 78, in from_frames
    res = _from_frames()
          ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/utils.py", line 61, in _from_frames
    return protocol.loads(
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/protocol/core.py", line 175, in loads
    return msgpack.loads(
           ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 130, in unpackb
    raise ValueError("Unpack failed: incomplete input")
ValueError: Unpack failed: incomplete input

CancelledError: ('repartitiontofewer-91bdf7eed289349cc448cc6908fceff3', 0)

In [ ]:
df4 = df.groupby("name").aggregate({"x": "sum", "y": "max"})
df4

In [ ]:
df4.compute().head(5)

In [ ]:
#在这里讲的dashboard

In [30]:
# benchmark
import dask
from dask.distributed import performance_report

with performance_report(filename="dask_report.html"):
    df = dask.datasets.timeseries(start='2000-01-01', end='2004-01-01')
    df.groupby(df.name).x.mean().compute()

/opt/anaconda3/lib/python3.12/site-packages/dask_expr/_collection.py:5833: UserWarning: dask_expr does not support the DataFrameIOFunction protocol for column projection. To enable column projection, please ensure that the signature of `func` includes a `columns=` keyword argument instead.
  warnings.warn(
2026-02-20 05:10:19,467 - distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/protocol/core.py", line 175, in loads
    return msgpack.loads(
           ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 136, in unpackb
    File-like object having `.read(n)` method.
msgpack.exceptions.ExtraData: unpack(b) received extra data.
2026-02-20 05:10:19,469 - distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/core.py", line 970, in _handle_comm
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/scheduler.py", line 5710, in add_client
    def validate_released(self, key: Key) -> None:
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/core.py", line 1025, in handle_stream
    raise

  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/tcp.py", line 247, in read
    try:

  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/utils.py", line 78, in from_frames
    res = _from_frames()
          ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/comm/utils.py", line 61, in _from_frames
    return protocol.loads(
           ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/distributed/protocol/core.py", line 175, in loads
    return msgpack.loads(
           ^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/msgpack/fallback.py", line 136, in unpackb
    File-like object having `.read(n)` method.
msgpack.exceptions.ExtraData: unpack(b) received extra data.
IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

CancelledError: ('repartitiontofewer-d1357858d5815558e764053b49517945', 0)